language: csharp
mono: none
dotnet: 2.0.0
script:
- dotnet restore
- dotnet build ./Licensing.sln
deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  skip_cleanup: true
  file: 
    - "./Licensing.Commons/bin/Release/netcoreapp2.0/Licensing.Commons.dll"
    - "./Licensing.Cli/bin/Release/netcoreapp2.0/Licensing.Cli.dll"
  on:
    repo: flostadler/Licensing
    tags: true
