language: csharp
mono: none
dotnet: 2.0.0
script:
- dotnet restore
- dotnet build -c Release ./Licensing.sln
- dotnet pack -c Release ./Licensing.Commons/Licensing.Commons.csproj
- zip -j ./release.zip ./Licensing.Commons/bin/Release/netcoreapp2.0/Licensing.Commons.dll ./Licensing.Cli/bin/Release/netcoreapp2.0/Licensing.Cli.dll ./Licensing.Commons/bin/Release/*.nupkg
addons:
  apt:
    packages:
    - zip
deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  skip_cleanup: true
  file: 
    - "./release.zip"
  on:
    repo: flostadler/Licensing
    tags: true
